### PR TITLE
Moved 'Friends of CodeSydney' to its own page.

### PR DESCRIPTION
**Pull request by QjStout**
## Rationale
As per discussion with @engramar, we aren't sure where to put the 'Friends of CodeSydney' section right now.
I have moved it to its own page, at least for the moment. We can revisit it in the future.

### CODE REVIEW

**Review by promie — APPROVED** [review]

**Review by engramar — APPROVED** [review]
Looks good @QjStout. As expected, we will expose the same banner across all pages (ie. logo and organisation name). Thanks.
Screen Shot 2020-08-28 at 9 24 35 am

**Comment by engramar** [comment]
I was thinking of getting new logos from all of them as the current ones are not of high quality.

**Comment by engramar** [comment]
We might also just change the format/presentation. Perhaps just their logos (no descriptions) with varying sizes and each one highlights on mouse hover.

**Comment by QjStout** [comment]
@engramar do you mean that you would like to display this banner at the top of every page?
banner

**Comment by engramar** [comment]
Correct @QjStout. That's my impression. I remember in Flask/Jinja you have the option to apply DRY(don't repeat yourself) approach where we put that header in a separate file and it is just called on top of every page (something like that).

**Comment by QjStout** [comment]
No problem @engramar.

**Pull request merged**
