### PR TITLE
84 create a page footer and add it to every page

### PR DESCRIPTION
**Pull request by chenhe-henry**
## Rationale

Add a footer to each page

## Advice for Reviewers & Testing Notes

- The background color of the footer is #3181B9(compare with the legacy site, #365877), which is the second one in our design.
- when hovering on the medias' icons, the color turns to #ff6347, feel free to give feedback about the hover color. 

## Screenshots:

- Add a screenshot or two of your changes, where applicable.
image

## Task Name

- #84 Create a page footer and add it to every page

## Linting Checklist
- [x] No commented code
- [x] Code Formatted nicely (Prettier)
- [x] PR your own code before you assign reviewers

### CODE REVIEW

**Review by QjStout — APPROVED** [review]
Oh man! I'm digging it @chenhe-henry.
What do you think @engramar?

**Comment by engramar** [comment]
Thanks @chenhe-henry @QjStout. Some comments below. 

1. I like the vibrant blue feel of the footer. Totally different from the old one which is more on the darker shade. 
2. Hover colour seems a bit off our colour theme. Perhaps just change it to a different shade of blue. 
3. Perhaps let us not make the footer text font bold. Hopefully it will not end up too thin and difficult to read. 
4. Let us make the 'Book with me' button the same vibrant blue colour as the footer. 

issue84-footer

**Review by engramar — CHANGES_REQUESTED** [review]
Thanks @chenhe-henry @QjStout. Some comments below.

- I like the vibrant blue feel of the footer. Totally different from the old one which is more on the darker shade.
- Hover colour seems a bit off our colour theme. Perhaps just change it to a different shade of blue.
- Perhaps let us not make the footer text font bold. Hopefully it will not end up too thin and difficult to read.
- Let us make the 'Book with me' button the same vibrant blue colour as the footer.

issue84-footer

**Comment by chenhe-henry** [comment]
@engramar @QjStout Thanks for your comments. 

I have done some modifications as below:

1. About the hover color, I compared the two colors on our style guide #191970 and #2DB6E3, and thought #191970 is better. 

2. Updated the 'book with me' button color to #3181B9, the same as footer color.

3. Updated the font-size and font-weight on footer text. Currently set font-weight as 400.

**Review by engramar — APPROVED** [review]
Looks good @chenhe-henry. Thanks.

issue84w

**Comment by QjStout** [comment]
Love it! Nice work man!

**Pull request merged**
