### PR TITLE
App bar

### LINKED ISSUE #75: Add banner to all pages
### Reference:
banner-requirement

### Note:
If it doesn't look good, we can use the current banner on the homepage and have a thin navbar type banner on other pages.

### LINKED ISSUE #87: Make a banner for non-homepages
The current banner on the Homepage is great but it's a bit too chunky for other pages.
We'll keep the current banner for the homepage and have a new thin banner bar for all other pages.

Make a thin white bar, hamburger menu button on the left and a codesydney logo and name in the center.

*** Reference:
thinbannerissue_LI

### PR DESCRIPTION
**Pull request by QjStout**
## Rationale
This is my suggestion for a new navbar & navigation menu.
If the design is approved, this would remove the need for issues #87 and #75.
I tried to make the old idea of a full-page navigation menu work but it just wasn't working out visually.
Likewise, I tried to work with the original design of a floating hamburger button but visually I found it to be much more appealing with a navbar.

## Advice for Reviewers & Testing Notes

- Navbar present and responsive
- Title in navbar redirects to homepage
- Hamburger button opens side draw
- All current router links + legacy site link present and functional

## Screenshots:
- New navbar
new-navbar

- New navigation menu
new-navmenu

## Task Name
- closes #87 
- closes #75

### CODE REVIEW

**Comment by QjStout** [comment]
Hey @engramar.

I ended up going in a much different direction with this than the original plan but I couldn't get the original plan to work and I feel that this has come out a lot stronger.

Let me know what you think.

**Comment by engramar** [comment]
No worries @QjStout . All good! You have full discretion for this project. Let me have a look at recent changes and let you know.

**Review by engramar — APPROVED** [review]
csnav

Looks good @QjStout . Some comments below for consideration in next iteration.
1. We can just retain the banner with 'Code.Sydney' on top and remove the one below the hexagon. 
2. In randomised focussed profile display, perhaps we should just add the role and badges as well. 
3.  In mobile view, it appears the profiles under 'Our People' are small. It should have been just a little bit smaller than the randomised focussed profile when browsing in mobile view.  
4. For the menu, perhaps we should remove the underline on each menu item. Also Align the 'Legacy Site' with the rest of the menu. 
5. I was thinking of hiding 'Friends' first and we just go live with two pages (homepage and Contact us) as a start. The reason being I have to revisit our informal partnership with them and whether it is still worth showing them. 
6. I am happy to go live with just the two pages and we just build on top of it at a later stage. 

Thanks again, Qj.

**Comment by QjStout** [comment]
Awesome @engramar.
A lot of those suggestions are already planned for future PRs.
I've made a note of the others.

**Review by chenhe-henry — APPROVED** [review]
Hi @QjStout, good job, love the consistent color and side draw navigation. 
Just thinking about changing the background-color of the contact page in the coming PRs. 
Anyway, the app bar for this PR is pretty good!

**Comment by QjStout** [comment]
Thanks @chenhe-henry.
Good point about the contact page. 
I'll note that.

**Pull request merged**
